server:
  port: 8080
spring:
  application:
    name: SpringBootApplication
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    #initialize: true
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: H2
    show-sql: true
    generate-ddl: false
management:
#  security:
#   enabled: false
#  endpoint:
#    health:
#      enabled: true
#      show-details: always
#  endpoints:
#    jmx:
#      exposure:
#       include: '*'
#    web:
#     exposure:
#      include: '*'
#      base-path: /actuator
#    cors:
#      allowed-origins: true
#      enabled-by-default: false